//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuvadava2023.Cotegory
{


    public partial class p18_MACHINE_TOOLS_SPARE_PARTS
    {
    }
}
